server:
  port: 8080
spring:
  mail:
    username: 18848826686@163.com
    password: Lichaoyuan521
    host: smtp.163.com
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
  redis:
    host: 139.155.83.172
    port: 6379
  datasource:
    url: jdbc:mysql://139.155.83.172:3306/news?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 50
    maxActive: 200
    maxWait: 60000
    minIdle: 20
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  rabbitmq:
    addresses: 139.155.83.172
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.zzuli.news.entity

logging:
  file: ../logs/springboot.log
  level:
    cn:
      zzuli:
        news:
          dao: DEBUG
